### PR TITLE
Add proper licensing.

### PR DESCRIPTION
**Pull request by samwightt**
This repo contains copyrighted code lifted from [Chorale](https://github.com/samwightt/chorale-renderer). However, it doesn't comply with the license of that repository (GPL V3). [Please see here for the text of the GPL V3 and how to comply with the license](https://www.gnu.org/licenses/gpl-3.0.en.html).

This pull request adds the proper copyright notices and licensing to the files that contain copyrighted code, modified or otherwise. It also updates the license of the repo to the one required by the GPL. [Please see here for why this is necessary.](https://www.quora.com/I-am-writing-software-licensed-under-MIT-and-including-GPL-software-Should-I-include-the-whole-GPL-license-text).

The following files were modified to add the required headers:
* `block.tsx`
* `renderer.tsx`
* `types.ts`

The new license is available in the `COPYING` file.

### CODE REVIEW

**Comment by mxstbr** [comment]
These files were copied on April 14th at 3:40pm in commit https://github.com/splitbee/react-notion/commit/beaf6f07b8754a64f1db0123501df31b1d09cd10. At that time, your entire repo was licensed as "ISC" as can clearly be seen in the package.json at that time: https://github.com/samwightt/chorale-renderer/blob/1e2c1415166e298c1ce72a1a15db927bebf2b5c8/package.json#L13

You only changed the license to GPL on April 14th at 10pm CEST in commit https://github.com/samwightt/chorale-renderer/commit/338cd497e28eefb1c924fc8c9c8143b57f2369c8, presumably after you noticed that somebody was actually using the code you wrote.

You can't change the license of a piece of code after-the-fact, that's not how it works. Only versions of the code after your commit changing the license are licensed under GPL.

As such, only attribution is required here. ISC is not a viral copyleft license, and this repo can be licensed as anything as long as @tobiaslins correctly attributes your code. That's all that needs to be changed here.

Don't be an open source dickhead please.

**Comment by samwightt** [comment]
Hi, thanks for the comment!

I'm sorry for the confusion, I wasn't aware that was the case (as evidenced by there being a lack of copyright notices on the repo before that commit), however you are right that I can't do anything about enforcing relicensing as the code was copied before that date. You are completely correct. Wasn't intending to be a dickhead, just wanted proper attribution for my work.

**Comment by timolins** [comment]
There are some similarities, which is to expect since the scope of the project is still the same. However, the rendering algorithm, as well as the other parts, are rewritten and not based on your code.

The only thing that is mostly the same (as your previously ISC licenced code) are the API typings, and we made sure to credit you for them.

We want to push the React Notion world forward and hope you do too.

**Comment by samwightt** [comment]
Ah I gotcha. Thanks so much for making that clear! I'm sorry to cause so much trouble, and I wish you the best on your project. Definitely let me know if you need any help with it in the future!

**Pull request closed without merging**
